
local_model:
  name: "Qwen/Qwen3-1.7B" # ["google/gemma-7b-it", "deepseek-ai/deepseek-llm-7b-chat", "Qwen/Qwen3-1.7B"]
  temperature: 0
  gpu_memory_utilization: 0.12
  gpu_device: "0"


api_model:
  #TODO


baseline_model:
  name: 'logreg' # ['logreg', 'knn', 'gboost', 'naive_argmax']
  all_names: ['logreg', 'gboost', 'rf']


data:
  DF_TYPE: 'openml' # ['custom', 'openml']
  DF_FORMAT: 'csv'
  DATASET_NAME: 'airbnb'
  DF_TRANSFORMATION_REGIME: 'no'
  LOCAL_DATASET_PATH: 'datasets/'
  TGEN_LOCAL_DATASET_PATH: 'datasets/agr_all_prompt1.csv'
  RESULT_PATH: 'results/experiments_result/'
  PROBS_PATH: 'results/llm_probs/'


experiment:
  baseline: False
  local_llm: True
  regime: 'local_nogen' # ['local_gen', 'local_nogen', 'api_gen']
  random_states_list: [864, 460, 142, 629, 761, 703, 24, 401, 210, 736]
  serialization_list: ['feat_val', 'feat_val_masked', 'html', 'markdown', 'markdown_masked']
  shot_list: [4, 8, 16, 32, 64]
  RATIO: '50/50'
  N_SHOTS: 0
  SAMPLING_REGIME: 'default'
  RANDOM_STATE: 42
  SCHEMA: '{"class": "0 or 1"}'
  THINKING: False
  CONFIG_CODE: configuration_code


openml:
  type: 'task' # ['task', 'dataset']
  df_openml: ['credit', 'transfusion', 'fitness', 'diabetes', 'biodegr', 'marketing']
  task: {'credit': 363626,
         'transfusion': 363621,
         'fitness': 363671,
         'diabetes': 363629,
         'biodegr': 363696,
         'marketing': 363684}
  dataset: {'telco': 42178,
            'pc4': 1049, 
            'tae': 955,
            'irish': 451,
            'compas': 42193, 
            'vote': 56,
            'cancer': 15,
            'steel': 1504,
            'kc1': 1067} 
